### ISSUE TITLE
Issues with unifiednlp location!!!  In android 9

### ISSUE THREAD

**Issue by Shabinder** [microg/UnifiedNlp#167]
Hello devs  , 
I want to let u know that our unified nlp no longer works perfect , as it is having issues in Android 9 , its working like a charm in oreo and below , but in android 9 if we install the standalone application there are issue in registering and binding it into system , but whenwe install microg using installer like nanodroid , the it registers into system but always show plzz check ur location backends nmand unified nlp has no location to test geocoders! 

I have given all the permission to it , and even using terminal  too , as describes in issue
https://github.com/microg/android_packages_apps_GmsCore/issues/366#issuecomment-427252345

So plz take a look into this and fix it if possible as many of the users are forced to be on oreo as there are compatibilty issue with pie!!

Also i have checked the same on 3 to 4 ROMs. 
And i the issue was same in all of them !

**Comment by Shabinder** [comment]
I am using following backends 
, moxilla backend , 
Deja vu location 
And nominatim , and all the oermissions are granted , checked twice for reassurance!

**Comment by skygate2012** [comment]
Same issue here.
