### ISSUE TITLE
Setting default backends when integrating with the system

### ISSUE THREAD

**Issue by chirayudesai** [microg/UnifiedNlp#190]
Hi,

I work on CalyxOS, and we ship microG by default.

We set `default_location_backends` and `default_geocoder_backends` to set the default backends, but I see that those have been removed in the latest version - https://github.com/microg/UnifiedNlp/commit/d0d3f500808981ce7ae451858f7a92012309b949#diff-6c6f7bef57a5890057a49ed6c6191676

Is there any plan to bring it back, or if not, is there any alternate method by which we can set this?

For reference, this is how we're setting it right now:
* https://gitlab.com/calyxos/platform_frameworks_base/-/commit/e18e804562a849da14e3ba84efe6f15d901ec41d
* https://gitlab.com/calyxos/vendor_calyx/-/commit/ca8a379d949f2ecb765e9c27b770b797db1ac165

**Comment by chirayudesai** [comment]
I noticed that you made a [commit](https://github.com/microg/UnifiedNlp/commit/3d5fc38ac1b3942b8ca48bd739c6c2fde317fabc) adding support for `/system/etc/microg.xml` a while ago, thanks!

We're shipping it now, https://gitlab.com/calyxos/platform_prebuilts_calyx/-/blob/2020.09.22.12/microg/microg.xml

For reference, this is basically the preferences file from /data on device. We ship the APKs as-is / unmodified / same signature from F-Droid, so that's what the signatures are.

One can verify using `apksigner verify --print-certs file.apk`

**Comment by mseleng** [comment]
Hi, I would like to know whether there has been any update on the docs regarding setting the default backend when UnifiedNlp is part of ROM. Thanks!
