### ISSUE TITLE
Local development workflow with GmsCore

### ISSUE THREAD

**Issue by chirayudesai** [microg/UnifiedNlp#196]
What is the expected local development workflow for testing this out?

We were able to build this and get aars, but so far trying to get them working with GmsCore hasn't been forthcoming.

https://github.com/CalyxOS/platform_external_microg_GmsCore/commit/9129c58de56c3293e5b436c9848620724999b002 is what we have right now, but a build with that leads to https://gist.github.com/mikeNG/cba815b58e2160104d62f3c5119a2c75

We still get APKs built even with the above errors anyway.

**Comment by chirayudesai** [comment]
We were working on this while trying to debug #195 

Not sure if this is the right place for the issue, or if this should be moved to GmsCore

**Comment by mar-v-in** [comment]
I'm not sure why you see this error.

The easiest way during development for me was to publish the UnifiedNlp to my local maven repository (`./gradlew publishReleasePublicationToMavenLocal`) and then adjust `ext.nlpVersion` and add `mavenLocal()` to subproject repositories in GmsCore's `build.gradle`.

**Comment by chirayudesai** [comment]
Thanks, that worked!

**Comment by chirayudesai** [comment]
Alternate version that we've switched over to make it one step: https://github.com/CalyxOS/platform_external_microg_GmsCore/commit/d7025ab7d3646bf3c10de093c6c216de57059046

Still need to fix CI, but it works fine otherwise.
