### ISSUE TITLE
How to apply the patch for Nougat or later

### ISSUE THREAD

**Issue by TearJoy** [microg/UnifiedNlp#213]
I'm just getting started to android customization. I've read that in android Nougat or later, you need to apply a patch so location can work correctly, I press the link and it brings me to the file. How do I exactly apply the patch file. I'm on Havoc 3.12 Android 10 X00T

**Comment by Ammako** [comment]
It's not really needed. If you have access to patching the relevant files, you have access to installing the apk directly into /system/priv-app instead.

**Comment by TearJoy** [comment]
yeah, i figured it out
