### ISSUE TITLE
20.15.16(120306-309763488) UnifiedNlp(NoGAPPS)

### ISSUE THREAD

**Issue by Crass420** [microg/UnifiedNlp#214]
**Affected app**
Name: UnifiedNlp(NoGAPPS)
Package id: github.com/microg/UnifiedNlp

**Describe the bug**
Clear and concise, OK..Downloaded F-Droid from their website and all of a sudden i get the Unified App downloaded for the hackers in my phone now to stalk and harass more. This not only app that miraculousky showed up either.

**To Reproduce**
There is no ateos cause i didnt download it so my steps are irrelevant..192.0.0.2 IP..come and enjoy.,hit me on email too

**Expected behavior**
Not having it in my phone.

**Screenshots**
Cant take screenshot.,they changed that setting.

**System**
Android Version: 10
Custom ROM: Should be stock but they hid a root in my phobe..i can get info again cuz i know where its hidden and how to divulge info

**microG**
microG Core version: 20.15.16
microG Self-Check results: N/A
<!--I cant even open it let alone look at checked boxes.

**Additional context**
Yeah i'll give permission, written, verbally, whatever to physically access info urself..u get rid of them..ill pay handsomely..only if and once jobs done n proof its taken care of.

**Comment by Crass420** [comment]
no i installed fdroid like normal from their website and went to settings n
set everything n then for hell of it clicked maintain applications in
fdroid settings n Unified(NoGapps) amongst a few others appeared n i cant
even delete them because no option sppears for it like any other app does
when downloaded on there.

On Friday, April 23, 2021, Felix Knecht ***@***.***> wrote:
> It is not clear what exactly happened from your description. Do you mean
that F-Droid showed you available updates and one of them is UnifiedNlp,
but you never installed UnifiedNlp?
> Let me guess: Your ROM has GoogleApps or OpenGapps or something like that
installed?
> If that is the case, FDroid mixes things up: It detects the Google Apps,
but thinks it is UnifiedNlp that is installed (they have to share some
identifier for technical reasons which confuses FDroid). So it offers to
update them.
>
> If this is what happened then the solution is easy: Just go to the
UnifiedNlp "page" in FDroid, select the "..." menu in the upper right
corner and touch "Ignore All Updates".
> And no worries: FDroid did not install UnifiedNlp. It just offered to
update it by mistake.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci6.googleusercontent.com/proxy/ilHERePuxknzxQZ-uz5IbvwGWqd0SaBNtZ1qRdaEgXLY4qGAi0WaYtZQDn6JCjtd6ApJI3bkXRMOR8KhX99QHXMrMsJvLiigzmnExk4vA1Hcy9N-E9KTo0omALverSSFKVvnYYvrdZusZT7PeaGqDlfkhOv-z0gYwUAdAv0gvOCQQwKUW_lYwfBZyNEbIsgKlpUdIGY9XkVhKptWGa2ffqapo6n_sp-hEks8eP1GMA=s0-d-e1-ft#https://github.com/notifications/beacon/ATZXZRPFWEKHYMYXYSPY5BTTKFPS5A5CNFSM43OKXJM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOGE257LY.gif>

**Comment by dicer** [comment]
Same thing: FDroid confuses your installed Google Apps with UnifiedNlp, cause they have to share package names. You can't uninstall, cause GApps is a system app, which can't be uninstalled by the user.
So all good. Just a labeling issue in FDroid.

**Comment by Crass420** [comment]
lol..ok well it doesnt explain the other 6 apps that folliwed right with
that n 2 in last 5 mins n all access and maliously just has permissions to
do whatever and magically none can be removed and are hidden deep inside a
root i nvr did on my phone either

On Friday, April 23, 2021, Felix Knecht ***@***.***> wrote:
> Same thing: FDroid confuses your installed Google Apps with UnifiedNlp,
cause they have to share package names. You can't uninstall, cause GApps is
a system app, which can't be uninstalled by the user.
> So all good. Just a labeling issue in FDroid.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/yrkpvZNUspqZda4_lkBDAz-t0xGEOW1R9fy4AUsJw_onvy2AaOqZ9waVZOxMRl_DYChCyoCLg2grLexJsGSEWdQa6X_FDBlyQvFXa2SKrC9bDkOvi2RnljT4qtKUKfvrTteISmKbmXWqilZONNWRJzodI028IX_p3QplQtMCMbgG2L2kl48cnsbF_R24NSyl71VRP774Lau2MYDiMjx_i1toKJX34z_GZXdxqugbww=s0-d-e1-ft#https://github.com/notifications/beacon/ATZXZRLYHKLP5VFEGZQAVL3TKFWSLA5CNFSM43OKXJM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOGE3GCYY.gif>

**Comment by Crass420** [comment]
Even in here man..i just had to close repos i nvr fucking made on shit about configuring my shit in here so they can control this shit as well..commenting on some chinese bullshit repo page explaining how to my ip n blah blah ....smh

**Comment by ale5000-git** [comment]
@dicer: The author of this issue is just a spammer, do not worry.
